version: '3.8'
services:
  customer:
    image: customer:latest
    container_name: customer
  product:
    image: product:latest
    container_name: product
  loadbalancer:
    image: nginx:latest
    container_name: nginx
    links:
      - customer
      - product
    ports:
        - '8000:8080'
